dmenu:addModifierLoader( function ()
dmenu:setRight('3',{
menuList = {
'ponLoid',
'ponSn',
'ponopticalinfo',
'ethWanConfig',
'tunnel4in6Config',
'tunnel6in4Config',
'l2tpConfig',
'localServiceCtrl',
'alg',
'dmz',
'portForwarding',
'portTrigger',
'ddns',
'portBinding',
'rip',
'multicastmode',
'igmp',
'mld',
'multicastbasic',
'multicastaddress',
'portlocate',
'lanMgrIpv6',
'routeIpv4',
'routeIpv6',
'upnp',
'bpdu',
'dns',
'voipBasic',
'voipServices',
'sipIf',
'sipAdvanced',
'sip',
'sipDigitmap',
'sipMedia',
'sipslc',
'sipCallerID',
'fax',
'voipqos',
'dialPlan',
'mgcpBasic',
'mgcpAuth',
'h248Basic',
'h248Auth',
'voipSwithPtcl',
'usbrestore',
'usbbackup',
'Wan3gConfig',
'logMgr',
'networkDiag',
'mirror',
'loopbackDetect',
'arpTable',
'macTable',
'ssmIPMapping',
'multicastvlan',
'IPv6SwitchMgr'},
pageList = {
{'filterCriteria','firewall_macfilterv3_t.lp'},
{'filterCriteria','firewall_urlfilter_m.lua'}
}
})
dmenu:removeList({
menuList = {'smNetSphereMAP'}
})
dmenu:newPage(
{
id="globalNat",
right=3,
name=lang.globalNAT01,
pageHelp=lang.globalNAT03,
areas={
{area="globalNAT_t.lp",backendFile="globalNAT_lua.lua"},
},
}
)
:insertAfter("internetConfig")
end)
